### ISSUE TITLE
fix vulnerabilities

### ISSUE THREAD

**Issue by Rihyx** [wormhole-foundation/wormhole-sdk-ts#480]
<img width="620" alt="Screenshot 2024-04-19 at 13 46 04" src="https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/18597956/d010c164-4646-4d0a-a96c-4d4c2ce2c072">

**Comment by barnjamin** [comment]
This is partially fixed in main, remaining 6 moderate are for @injective/sdk-ts dep on axios@0.27.2
