### ISSUE TITLE
malformed transaction on a usdt transfer from from Oasis to Ethereum

### ISSUE THREAD

**Issue by MarcoMandar** [wormhole-foundation/wormhole-sdk-ts#534]
I keep getting a malformed transaction when trying to bridge Usdtet from oasis to Usdt on ethereum.
![image](https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/70625671/dc606420-7e9c-4726-9f0f-402e8e49e469)

**Comment by barnjamin** [comment]
What signer are you using?

**Comment by MarcoMandar** [comment]
i am using this
export async function getSigner<N extends Network, C extends Chain>(
  chain: ChainContext<N, C>,
): Promise<SignerStuff<N, C>> {
  // Read in from `.env`
  (await import('dotenv')).config();

  // const platform = chain.platform.utils()._platform;
  // const evm = await platform();
  const signer: Signer = await evm.getSigner(
    await chain.getRpc(),
    getEnv('PRIVATE_KEY'),
  );

  return {
    chain,
    signer: signer as Signer<N, C>,
    address: Wormhole.chainAddress(chain.chain, signer.address()),
  };
}

**Comment by barnjamin** [comment]
I can repro but pasting the tx contents into the txdecoder I'd expect it to fail 🤔 

![image](https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/520236/eb485660-b1d5-4d4d-8898-69e84ec6a5d2)

Do you often use Oasis? are there any gotchas for tx formatting?

**Comment by MarcoMandar** [comment]
No this is the first time I am using it, I have done a transaction to test, using the portal token bridge it worked fine https://explorer.oasis.io/mainnet/emerald/tx/0xde646172c18a8344c2d2931e53480765042051e7bd76c9f4a281a1bfffd6d25a
the Raw Data is: 0x0f5287b0000000000000000000000000dc19a122e268128b5ee20366299fc7b5b199c8e300000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000903a1bd58e377f70f5cf501b76134e71b218d5aa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000feb00000

**Comment by barnjamin** [comment]
![image](https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/520236/d59903b7-2584-41ef-8b57-cd140c9d10be)
🤔 🤔 🤔

**Comment by MarcoMandar** [comment]
i used the portal https://portalbridge.com/advanced-tools/#/transfer to do it, maybe it is different

**Comment by barnjamin** [comment]
On portal bridge, you'd be using a signer like metamask or something which probably has some additional logic to produce a transaction that is valid for Oasis. 

Will need to dig around to figure out what else needs to be done for Oasis txs

**Comment by MarcoMandar** [comment]
I used the wrap from https://github.com/oasisprotocol/sapphire-paratime/blob/main/examples/ethersv5-ts-esm/src/index.ts but it still give the same error

**Comment by MarcoMandar** [comment]
0x5cb79841171e3cbe9706ebeb0daceb7adbf110d231a9f9d994711ec624de29ea this worked but it had to be using 
                t = {
                    ...transaction,
                    ...{
                        value: '0',
                        gasPrice: '100000000000',
                        gasLimit: '300000',
                        nonce: await this._signer.getNonce(),
                    },
                }
                and using  const tx = await this._signer.sendTransaction(t);
                broadcasting the rawTransaction does not work, could you help me with this?
                
![image](https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/70625671/edf4b3a6-d1a1-4561-9e85-fa420b1df8fb)

**Comment by MarcoMandar** [comment]
> ![image](https://private-user-images.githubusercontent.com/520236/329402223-d59903b7-2584-41ef-8b57-cd140c9d10be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDA0NDgsIm5iZiI6MTcxNTU0MDE0OCwicGF0aCI6Ii81MjAyMzYvMzI5NDAyMjIzLWQ1OTkwM2I3LTI1ODQtNDFlZi04YjU3LWNkMTQwYzlkMTBiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxODU1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWVkM2NkMTI5MGE3N2M4YzgwYjU3YzEwN2RiYmNlNTNmMjQxNjJiMzBiZDUxZjExMmQzYzRhMWUwNTMzZTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S1pbRrcDWdhiFLaCMJqYpocciVAK9wKyIJlLL4FbM-0) 🤔 🤔 🤔



> On portal bridge, you'd be using a signer like metamask or something which probably has some additional logic to produce a transaction that is valid for Oasis.
> 
> Will need to dig around to figure out what else needs to be done for Oasis txs

So I succeded by modifying the signer and platform from the wormhole sdk by modifying the sign in signer and sendWait in platform .
if I provide the changes can you add them to the sdk ?

**Comment by barnjamin** [comment]
I'm curious to see what changes are necessary

I should have linked [this](https://github.com/barnjamin/ezui) before but wrapping a web signer like metamask may be all you need to do

**Comment by MarcoMandar** [comment]
async sign(tx) {
          const signed = [];
          const gasLimit = this.opts?.maxGasLimit ?? 500000n;
          let maxFeePerGas = 1500000000n; // 1.5 gwei
          let maxPriorityFeePerGas = 100000000n; // 0.1 gwei
          if (this.chain() !== 'Celo') {
              const feeData = await this._signer.provider.getFeeData();
              maxFeePerGas = feeData.maxFeePerGas ?? maxFeePerGas;
              maxPriorityFeePerGas = feeData.maxPriorityFeePerGas ?? maxPriorityFeePerGas;
          }
          for (const txn of tx) {
              const { transaction, description } = txn;
              if (this.opts?.debug)
                  console.log(`Signing: ${description} for ${this.address()}`);
              let t = {};
              if (this.chain() === 'Oasis') {
                  t = {
                      ...transaction,
                      gasPrice: '100000000000',
                      gasLimit: '300000',
                      nonce: await this._signer.getNonce(),
                  };
              } else {
                  t = {
                      ...transaction,
                      maxFeePerGas,
                      maxPriorityFeePerGas,
                      gasLimit,
                      nonce: await this._signer.getNonce(),
                  };
              }
              if (this.chain() === 'Oasis') {
                  const oasisT = { t, signer: this._signer };
                  signed.push(oasisT);
              } else {
                  signed.push(await this._signer.signTransaction(t));
              }
          }
          return signed;
      }
      for the signer and
      static async sendWait(chain, rpc, stxns) {
           const txhashes = [];
           for (const stxn of stxns) {
               let txRes;
               if (chain === 'Oasis') {
                   const { signer, t } = stxn;
                   txRes = await signer.sendTransaction(t);
                   txhashes.push(txRes.hash);
               } else {
                   txRes = await rpc.broadcastTransaction(stxn);
                   txhashes.push(txRes.hash);
               }
               if (chain === 'Celo') {
                   console.error('TODO: override celo block fetching');
                   continue;
               }
               const txReceipt = await txRes.wait();
               if (txReceipt === null)
                   throw new Error('Received null TxReceipt');
           }
           return txhashes;
       } for the platform are the changes

**Comment by barnjamin** [comment]
after some debugging, I found that by setting the legacy gas params AND setting type to `0` in the transaction allows the tx to be parsed properly by Oasis


https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/535/commits/1963d50098c7b1f04994f6bc799295088c8fd181

**Comment by MarcoMandar** [comment]
> after some debugging, I found that by setting the legacy gas params AND setting type to `0` in the transaction allows the tx to be parsed properly by Oasis
> 
> [1963d50](https://github.com/wormhole-foundation/wormhole-sdk-ts/commit/1963d50098c7b1f04994f6bc799295088c8fd181)

yes I had to set it to legacy, but even broadcast did not work, is this merged into the sdk now?

**Comment by barnjamin** [comment]
It is now merged, and once the publish action finishes it will be available 

https://github.com/wormhole-foundation/wormhole-sdk-ts/releases/tag/0.6.9-beta.0

**Comment by MarcoMandar** [comment]
> It is now merged, and once the publish action finishes it will be available
> 
> https://github.com/wormhole-foundation/wormhole-sdk-ts/releases/tag/0.6.9-beta.0

I am just running a script that changes the sdk for now
