### ISSUE TITLE
There are two parsing errors.

### ISSUE THREAD

**Issue by daoauth** [wormhole-foundation/wormhole-sdk-ts#542]
ERROR in ./node_modules/@wormhole-foundation/sdk-solana-core/dist/esm/utils/program.js
<img width="1088" alt="Screenshot 2024-05-10 at 9 27 00 PM" src="https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/57783762/372c5b4f-9e9a-4a83-a2e7-e7877fbac069">

ERROR in ./node_modules/@wormhole-foundation/sdk-solana-tokenbridge/dist/esm/utils/tokenBridge/program.js
<img width="913" alt="Screenshot 2024-05-10 at 9 28 37 PM" src="https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/57783762/be907a58-3698-4b1b-9047-181c8e07d596">

**Comment by barnjamin** [comment]
You should be able to ignore these with skipLibCheck in the tsconfig for now but will take a look

**Comment by barnjamin** [comment]
@duckpost can you post the relevant config params you've got? package.json type, tsconfig module/moduleResolution and bundler stuff

**Comment by barnjamin** [comment]
going to consider this resolved once https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/550 is in a release.

Instead of finding a way to both assert the type for newer node/ts/js, I just swapped out the json for a constant to represent the IDL

**Comment by nuzelac** [comment]
I can confirm no issues with this on 0.7.0-beta.0, optimism cctp works too 👍
