### ISSUE TITLE
error scaleAmount

### ISSUE THREAD

**Issue by MarcoMandar** [wormhole-foundation/wormhole-sdk-ts#580]
I am getting Error: scaleAmount

**Comment by barnjamin** [comment]
I'll need some more here to help debug

**Comment by MarcoMandar** [comment]
![image](https://github.com/wormhole-foundation/wormhole-sdk-ts/assets/70625671/d0aff348-1afa-4642-9717-a3882efcb9e4)
this is the error

**Comment by barnjamin** [comment]
did you try truncateAmount?

the issue is that scale will not automatically cut off nonzero digits so going from 8 to 6 would cut off the last `10` and we decided that was bad

**Comment by MarcoMandar** [comment]
yes i did but the sdk gets the amount again from the txhash i had to modify the sdk and add a truncateAmount function

**Comment by barnjamin** [comment]
can you send the txid for that transaction please?

**Comment by nullbitx8** [comment]
I'm running into this now as well.
The default behavior of the [fromTransaction](https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/connect/src/protocols/tokenBridge/tokenTransfer.ts#L195) function is to take the amount from the VAA and create an amount with 8 decimals.

Say you're sending 0.001000 USDC (6 decimals), `fromTransaction` and therefore [fromIdentifier](https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/connect/src/protocols/tokenBridge/tokenTransfer.ts#L154) creates an [amount with 8 decimals](https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/connect/src/protocols/tokenBridge/tokenTransfer.ts#L168) and then tries to scale it from 8 to 6.

What is the correct way of doing this if you want to use `fromTransaction`? 
Perhaps adding an optional `truncate` flag to `fromTransaction` that defaults to `false`?

Or is it better to take another route?
