### ISSUE TITLE
TokenTransfer.getTransferVaa mixes up results when doing several queries in a loop.

### ISSUE THREAD

**Issue by mmaurello** [wormhole-foundation/wormhole-sdk-ts#655]
Hello Wormhole team. 

I'm having an issue with the sdk. I'm doing a call to the tx history with `wh.getTransactionsForAddress` and then iterating inside the array obtained, to fetch the VAA for each of the transactions. What I'm getting are mixed up tx ids with the resulting VAA. 

I created a small sample in CodeSandbox where I replicated minimally the code in my app. 
To see it [click here to go to CodeSandbox](https://codesandbox.io/p/sandbox/wormhole-vaa-pjlxks?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzh71ddp0006356v98182cpc%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzh71ddp0002356vjhon6dwu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzh71ddp0003356vxg0x9e73%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzh71ddp0005356vxnjikofr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzh71ddp0002356vjhon6dwu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzh71ddp0001356vdnvx7dxu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzh71ddp0002356vjhon6dwu%2522%252C%2522activeTabId%2522%253A%2522clzh71ddp0001356vdnvx7dxu%2522%257D%252C%2522clzh71ddp0005356vxnjikofr%2522%253A%257B%2522id%2522%253A%2522clzh71ddp0005356vxnjikofr%2522%252C%2522activeTabId%2522%253A%2522clzh7wuf4006o356v2e474pu2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzh71ddp0004356vie2arnka%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzh7wuf4006o356v2e474pu2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzh71ddp0003356vxg0x9e73%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzh71ddp0003356vxg0x9e73%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and open the incorporated console where I log the results. 

As you can see I obtain mixed up results and wrong VAAs that can be checked in WormholeScan 
For example here I can check that for this TxId the VAA sequence is 2034 https://wormholescan.io/#/tx/0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11?network=TESTNET&view=advanced
And I'm getting different values in my example
`for tx 0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11 the VAA sequence is 1214
for tx 0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11 the VAA sequence is 2034
for tx 0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11 the VAA sequence is 1212
for tx 0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11 the VAA sequence is 2034
for tx 0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11 the VAA sequence is 2040
for tx 0xf89ea12b4ecdba9e5ec522a02f876d84ecb5bf8625963cbbb8c4bf36422e4c11 the VAA sequence is 2034`

**Comment by kev1n-peters** [comment]
This was an issue with Wormholescan and has been fixed.
