### ISSUE TITLE
CCTP transfer to Solana does not work if the target wallet USDC ATA is not already created

### ISSUE THREAD

**Issue by evgeniko** [wormhole-foundation/wormhole-sdk-ts#691]
The following error message is returned when the target wallet on Solana does not have an already created usdc associated token account. So a USDC transfer from Chain X to Solana, will always fail with that at the moment, with the sdk.

```
transactionMessage: 'Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4',
transactionLogs: [
  'Program CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd invoke [1]',
  'Program log: Instruction: ReceiveMessage',
  'Program CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3 invoke [2]',
  'Program log: Instruction: HandleReceiveMessage',
  'Program log: AnchorError caused by account: recipient_token_account. Error Code: AccountNotInitialized. Error Number: 3012. Error Message: The program expected this account to be already initialized.',
  'Program CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3 consumed 10141 of 60551 compute units',
  'Program CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3 failed: custom program error: 0xbc4',
  'Program CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd consumed 149590 of 200000 compute units',
  'Program CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd failed: custom program error: 0xbc4'
]
```

**Comment by laalauren1** [comment]
@evgeniko You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana live support](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by obumnwabude** [comment]
@evgeniko This seems not to be specific to USDC, but to all SPL tokens seemingly. If you also send ETH from Sepolia, as it arrives Solana as WETH, the same error is thrown.

**Comment by kev1n-peters** [comment]
Fixed in https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/692
